# Generated by Django 2.0.13 on 2019-05-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_auto_20190521_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Autor',
            field=models.ManyToManyField(to='libros.Autor'),
        ),
    ]
