# Generated by Django 2.0.13 on 2019-05-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
